const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.join(__dirname,'..');
function runtime(){const c={window:{}};vm.createContext(c);for(const name of ['core/music-theory','instruments/guitar','instruments/bass-4','instruments/ukulele','core/fretboard-engine','core/play-exercises']){vm.runInContext(fs.readFileSync(path.join(base,name+'.js'),'utf8'),c);Object.assign(c,c.window)}return c}
test('All instrument/style/level/key phrases fit the neck and resolve on the root',()=>{const c=runtime();let count=0;for(const profile of Object.values(c.FRETBOARD_INSTRUMENTS)){const engine=c.FretboardEngine.createInstrumentEngine(profile);for(const style of c.PlayExercises.styles)for(const level of c.PlayExercises.levels)for(const root of c.MusicTheory.NOTES)for(const authored of c.PlayExercises.list(profile.family,style,level)){const e=c.PlayExercises.transpose(authored,root,engine),scale=c.MusicTheory.pentatonicPCs(c.MusicTheory.PC[root],'minor');for(const n of e.notes){assert.ok(n.fret>=0&&n.fret<=engine.maxFret);assert.ok(scale.includes(engine.noteAt(n.string,n.fret)));if(n.bend)assert.ok(scale.includes(c.MusicTheory.mod(engine.noteAt(n.string,n.fret)+n.bend)))}const last=e.notes.at(-1);assert.equal(engine.noteAt(last.string,last.fret),c.MusicTheory.PC[root]);count++}}assert.equal(count,1728)});
test('Connected techniques use one string and the correct direction',()=>{const c=runtime();for(const profile of Object.values(c.FRETBOARD_INSTRUMENTS))for(const style of c.PlayExercises.styles)for(const level of c.PlayExercises.levels)for(const e of c.PlayExercises.list(profile.family,style,level))e.notes.forEach((n,i)=>{if(['h','p','/','\\'].includes(n.technique)){assert.equal(n.string,e.notes[i-1].string);assert.equal(n.fret>e.notes[i-1].fret,['h','/'].includes(n.technique))}if(profile.family!=='guitar')assert.notEqual(n.technique,'b');if(level==='Beginner')assert.equal(n.technique,null)})});
test('Guitar A minor example matches the approved seven-note descending lick',()=>{const c=runtime();const e=c.PlayExercises.list('guitar','Blues','Beginner')[0];assert.equal(JSON.stringify(e.notes.map(n=>[n.string,n.fret])),JSON.stringify([[5,8],[5,5],[4,8],[4,5],[3,7],[3,5],[2,7]]))});
test('Daily exercise is stable through a local calendar day',()=>{const c=runtime();assert.equal(c.PlayExercises.dailyIndex(new Date(2026,9,6,1)),c.PlayExercises.dailyIndex(new Date(2026,9,6,23)));assert.notEqual(c.PlayExercises.dailyIndex(new Date(2026,9,6)),c.PlayExercises.dailyIndex(new Date(2026,9,7)))});
function sessionRuntime(storage){const c=runtime(),nodes=new Map();class Node{constructor(){this.children=[];this.events={};this.attrs={};this.classes=new Set();this.classList={toggle:(k,on)=>on?this.classes.add(k):this.classes.delete(k)};this.textContent='';this.hidden=false}append(n){this.children.push(n)}replaceChildren(){this.children=[]}querySelectorAll(){return this.children}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,f){this.events[k]=f}click(){this.events.click?.()}}
const root={querySelector:s=>{if(!nodes.has(s))nodes.set(s,new Node());return nodes.get(s)}};c.document={createElement:()=>new Node()};c.localStorage=storage;c.PlayRenderer={render:(_,exercise)=>{c.lastExercise=exercise}};c.PlayExercises={...c.PlayExercises,dailyIndex:()=>0};vm.runInContext(fs.readFileSync(path.join(base,'core/play-session.js'),'utf8'),c);const engine=c.FretboardEngine.createInstrumentEngine(c.FRETBOARD_INSTRUMENTS.guitar);const session=c.window.PlaySession.create({root,engine,refreshControls(){}});return{session,nodes,c}}
test('Self-validation saves once, next advances, and retry keeps the current lick',()=>{let saved;const storage={getItem:()=>saved,setItem:(_,v)=>saved=v};let r=sessionRuntime(storage);r.session.enter();const original=r.c.lastExercise.id;r.nodes.get('#playPracticing').click();assert.equal(r.c.lastExercise.id,original);assert.match(r.nodes.get('#playStatus').textContent,/Take your time/);r.nodes.get('#playGotIt').click();assert.equal(JSON.parse(saved).length,1);assert.match(r.nodes.get('#playProgress').textContent,/1 licks completed/);assert.equal(r.nodes.get('#playGotIt').textContent,'✓ Next lick');r=sessionRuntime(storage);r.session.enter();assert.equal(r.nodes.get('#playGotIt').textContent,'✓ Next lick');r.nodes.get('#playGotIt').click();assert.notEqual(r.c.lastExercise.id,original);assert.equal(JSON.parse(saved).length,1);r.nodes.get('#playLevelControls').children[2].click();r.nodes.get('#playPracticing').click();assert.equal(r.nodes.get('#playSimpler').hidden,false);r.nodes.get('#playSimpler').click();assert.match(r.c.lastExercise.id,/Intermediate/)});
test('Storage failures do not block practice or self-validation',()=>{const r=sessionRuntime({getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}});r.session.enter();r.nodes.get('#playGotIt').click();assert.match(r.nodes.get('#playProgress').textContent,/Saving unavailable/);assert.equal(r.nodes.get('#playGotIt').textContent,'✓ Next lick')});
test('Shared drawer is exposed inline and inert only when closed in compact mode',()=>{const nodes=new Map(),media={matches:false,addEventListener(_,f){this.change=f}},c={window:{},matchMedia:()=>media};function node(id){if(!nodes.has(id)){const classes=new Set();nodes.set(id,{attrs:{},events:{},classList:{contains:k=>classes.has(k),toggle:(k,on)=>on?classes.add(k):classes.delete(k)},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.events[k]=f},focus(){c.focused=id}})}return nodes.get(id)}const root={querySelector:node};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(base,'core/controls.js'),'utf8'),c);c.window.FretboardControls.bindDrawer({root,name:'play'});const drawer=node('#playDrawer'),btn=node('#playMenuBtn');assert.equal(drawer.inert,false);assert.equal(drawer.attrs['aria-hidden'],'false');media.matches=true;media.change();assert.equal(drawer.inert,true);btn.events.click();assert.equal(drawer.inert,false);assert.equal(btn.attrs['aria-expanded'],'true');drawer.events.keydown({key:'Escape',preventDefault(){}});assert.equal(drawer.inert,true);assert.equal(c.focused,'#playMenuBtn');media.matches=false;media.change();assert.equal(drawer.inert,false)});
