const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function runtime(desktop=false){
 class Node{constructor(){this.children=[];this.style={};this.events={};this.dataset={};this.classList={toggle(){}};this.hidden=false;this.inert=false;this.innerHTML='';this.attrs={};this.selected={}}append(n){this.children.push(n);n.parentElement=this}querySelector(s){return this.selected[s]??=new Node()}querySelectorAll(){return this.children}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,f){this.events[k]=f}cloneNode(){const n=new Node();n.src=this.src;return n}focus(){c.document.activeElement=this}}
 const menus=['Learn','Daily Routine','Fretboard Map','Circle of Fifths','Quiz'].map((title,i)=>{const n=new Node();n.querySelector('.home-card-copy strong').textContent=title;n.querySelector('.hero-icon img').src='icon-'+i;return n});
 const app=new Node(),media={matches:desktop,addEventListener(){}};
 const c={window:{},URL,URLSearchParams,TextEncoder,console,matchMedia:()=>media,document:{head:new Node(),body:{dataset:{}},createElement:()=>new Node(),querySelector:()=>app,querySelectorAll:()=>menus,addEventListener(){}}};vm.createContext(c);for(const file of ['web/vendor/qrcode.js','web/core/modal.js','web/core/access.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c);return {c,app,menus,Access:c.window.FretboardAccess};
}
test('Store destinations follow the chosen instrument and reject missing/non-HTTPS links',()=>{const {Access}=runtime();const config={instrument:'bass-4',stores:{guitar:{android:'https://example.com/guitar'},'bass-4':{android:'https://play.google.com/store/apps/details?id=bass',ios:'https://apps.apple.com/app/id123'}}};assert.match(Access.storeUrl(config,'android'),/id=bass/);assert.match(Access.storeUrl(config,'ios'),/id123/);assert.equal(Access.storeUrl({...config,instrument:'ukulele'},'android'),null);for(const url of ['javascript:alert(1)','http://example.com','not a URL'])assert.equal(Access.storeUrl({instrument:'guitar',stores:{guitar:{android:url}}},'android'),null)});
test('Local QR SVG contains a four-module quiet zone and represents its exact destination',()=>{const {c,Access}=runtime();const urls=['https://play.google.com/store/apps/details?id=com.example.guitar','https://apps.apple.com/app/id123456'];for(const url of urls){const qr=new c.window.FretboardQRCode(-1,1);qr.addData(url);qr.make();const svg=Access.qrSvg(url),n=qr.getModuleCount();assert.ok(svg.includes(`viewBox="0 0 ${n+8} ${n+8}"`));for(let y=0;y<n;y++)for(let x=0;x<n;x++)assert.equal(svg.includes(`M${x+4} ${y+4}h1v1h-1z`),qr.isDark(y,x))}assert.notEqual(Access.qrSvg(urls[0]),Access.qrSvg(urls[1]))});
test('Unlock dialog keeps two direct store buttons and no QR for missing destinations',()=>{const {Access,app}=runtime();Access.mount({instrument:'guitar',stores:{guitar:{android:'',ios:''}}},Access.create(false));const overlay=app.children[0],columns=overlay.querySelector('.premium-stores').children;assert.equal(columns.length,2);assert.match(overlay.innerHTML,/FRETBOARD SKILLS/);assert.doesNotMatch(overlay.innerHTML,/€|Coming soon/);for(const column of columns){assert.equal(column.children.length,1);assert.equal(column.children[0].disabled,true)}assert.match(columns[0].children[0].innerHTML,/Google Play/);assert.match(columns[1].children[0].innerHTML,/App Store/)});
test('Desktop builds distinct QR codes lazily on opening, mobile keeps them ungenerated',async()=>{for(const desktop of [false,true]){const {Access,app}=runtime(desktop);const modal=Access.mount({instrument:'guitar',stores:{guitar:{android:'https://example.com/android',ios:'https://example.com/ios'}}},Access.create(false));const cols=app.children[0].querySelector('.premium-stores').children;assert.equal(cols[0].children[0].href,'https://example.com/android');assert.equal(cols[1].children[0].href,'https://example.com/ios');for(const col of cols)assert.equal(col.children[1].querySelector('div').innerHTML,'');modal.open();await Promise.resolve();const qr=cols.map(col=>col.children[1].querySelector('div').innerHTML);if(desktop){assert.match(qr[0],/<svg/);assert.notEqual(qr[0],qr[1])}else assert.deepEqual(qr,['',''])}});

test('Unlock menus follow home labels, artwork and order including future menus',()=>{const {Access,app,menus}=runtime();const extra=menus[0].cloneNode();extra.querySelector('.home-card-copy strong').textContent='New menu';extra.querySelector('.hero-icon img').src='new.svg';menus.push(extra);Access.mount({instrument:'guitar'},Access.create(false));const items=app.children[0].querySelector('.premium-skills').children;assert.equal(items.length,6);for(let i=0;i<menus.length;i++){assert.equal(items[i].children[1].textContent,menus[i].querySelector('.home-card-copy strong').textContent);assert.equal(items[i].children[0].src,menus[i].querySelector('.hero-icon img').src);assert.notEqual(items[i].children[0],menus[i].querySelector('.hero-icon img'))}});
